# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'board.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from classes.layout_methods_inserter import LayoutMethodsInserter
from classes.tile_button_decoder import TileButtonDecoder

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_Dialog(object):
    def tile_click(self, button):
        button_name = button.objectName()
        tile_index, color, is_home_tile, is_starting_tile = TileButtonDecoder.decode_button_name(button_name)
        a = 5

    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1280, 720)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(1280, 720))
        Dialog.setMaximumSize(QtCore.QSize(1280, 720))
        self.label = QtGui.QLabel(Dialog)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(-4, 0, 1280, 720))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1280, 720))
        self.label.setMaximumSize(QtCore.QSize(1280, 720))
        self.label.setSizeIncrement(QtCore.QSize(1280, 720))
        self.label.setBaseSize(QtCore.QSize(1280, 720))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("../graphics/board.png")))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.blue_starting_tile_0 = QtGui.QPushButton(Dialog)
        self.blue_starting_tile_0.setGeometry(QtCore.QRect(191, 70, 41, 41))
        self.blue_starting_tile_0.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                          "border-image: url(../graphics/counter-blue.png);\n"
                                                          "background-repeat:no-repeat;"))
        self.blue_starting_tile_0.setText(_fromUtf8(""))
        self.blue_starting_tile_0.setObjectName(_fromUtf8("blue_starting_tile_0"))
        self.blue_starting_tile_1 = QtGui.QPushButton(Dialog)
        self.blue_starting_tile_1.setGeometry(QtCore.QRect(241, 70, 41, 41))
        self.blue_starting_tile_1.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                          "background-image: url(../graphics/counter-blue.png);\n"
                                                          "background-repeat:no-repeat;"))
        self.blue_starting_tile_1.setText(_fromUtf8(""))
        self.blue_starting_tile_1.setObjectName(_fromUtf8("blue_starting_tile_1"))
        self.blue_starting_tile_2 = QtGui.QPushButton(Dialog)
        self.blue_starting_tile_2.setGeometry(QtCore.QRect(191, 121, 41, 41))
        self.blue_starting_tile_2.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                          "border-image: url(../graphics/counter-blue.png);\n"
                                                          "background-repeat:no-repeat;"))
        self.blue_starting_tile_2.setText(_fromUtf8(""))
        self.blue_starting_tile_2.setObjectName(_fromUtf8("blue_starting_tile_2"))
        self.blue_starting_tile_3 = QtGui.QPushButton(Dialog)
        self.blue_starting_tile_3.setGeometry(QtCore.QRect(241, 121, 41, 41))
        self.blue_starting_tile_3.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                          "border-image: url(../graphics/counter-blue.png);\n"
                                                          "background-repeat:no-repeat;"))
        self.blue_starting_tile_3.setText(_fromUtf8(""))
        self.blue_starting_tile_3.setObjectName(_fromUtf8("blue_starting_tile_3"))
        self.yellow_starting_tile_0 = QtGui.QPushButton(Dialog)
        self.yellow_starting_tile_0.setGeometry(QtCore.QRect(191, 548, 42, 43))
        self.yellow_starting_tile_0.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.yellow_starting_tile_0.setAutoFillBackground(False)
        self.yellow_starting_tile_0.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                            "background-image: url(../graphics/counter-yellow.png);\n"
                                                            "background-repeat:no-repeat;"))
        self.yellow_starting_tile_0.setText(_fromUtf8(""))
        self.yellow_starting_tile_0.setObjectName(_fromUtf8("yellow_starting_tile_0"))
        self.yellow_starting_tile_1 = QtGui.QPushButton(Dialog)
        self.yellow_starting_tile_1.setGeometry(QtCore.QRect(241, 548, 43, 43))
        self.yellow_starting_tile_1.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                            "background-image: url(../graphics/counter-yellow.png);\n"
                                                            "background-repeat:no-repeat;"))
        self.yellow_starting_tile_1.setText(_fromUtf8(""))
        self.yellow_starting_tile_1.setObjectName(_fromUtf8("yellow_starting_tile_1"))
        self.yellow_starting_tile_2 = QtGui.QPushButton(Dialog)
        self.yellow_starting_tile_2.setGeometry(QtCore.QRect(191, 598, 43, 43))
        self.yellow_starting_tile_2.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                            "background-image: url(../graphics/counter-yellow.png);\n"
                                                            "background-repeat:no-repeat;"))
        self.yellow_starting_tile_2.setText(_fromUtf8(""))
        self.yellow_starting_tile_2.setObjectName(_fromUtf8("yellow_starting_tile_2"))
        self.yellow_starting_tile_3 = QtGui.QPushButton(Dialog)
        self.yellow_starting_tile_3.setGeometry(QtCore.QRect(241, 598, 43, 45))
        self.yellow_starting_tile_3.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                            "background-image: url(../graphics/counter-yellow.png);\n"
                                                            "background-repeat:no-repeat;"))
        self.yellow_starting_tile_3.setText(_fromUtf8(""))
        self.yellow_starting_tile_3.setObjectName(_fromUtf8("yellow_starting_tile_3"))
        self.green_starting_tile_0 = QtGui.QPushButton(Dialog)
        self.green_starting_tile_0.setGeometry(QtCore.QRect(673, 548, 43, 44))
        self.green_starting_tile_0.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                           "background-image: url(../graphics/counter-green.png);\n"
                                                           "background-repeat:no-repeat;"))
        self.green_starting_tile_0.setText(_fromUtf8(""))
        self.green_starting_tile_0.setObjectName(_fromUtf8("green_starting_tile_0"))
        self.green_starting_tile_1 = QtGui.QPushButton(Dialog)
        self.green_starting_tile_1.setGeometry(QtCore.QRect(723, 548, 43, 44))
        self.green_starting_tile_1.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                           "background-image: url(../graphics/counter-green.png);\n"
                                                           "background-repeat:no-repeat;"))
        self.green_starting_tile_1.setText(_fromUtf8(""))
        self.green_starting_tile_1.setObjectName(_fromUtf8("green_starting_tile_1"))
        self.green_starting_tile_2 = QtGui.QPushButton(Dialog)
        self.green_starting_tile_2.setGeometry(QtCore.QRect(672, 598, 43, 44))
        self.green_starting_tile_2.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                           "background-image: url(../graphics/counter-green.png);\n"
                                                           "background-repeat:no-repeat;"))
        self.green_starting_tile_2.setText(_fromUtf8(""))
        self.green_starting_tile_2.setObjectName(_fromUtf8("green_starting_tile_2"))
        self.green_starting_tile_3 = QtGui.QPushButton(Dialog)
        self.green_starting_tile_3.setGeometry(QtCore.QRect(723, 598, 43, 44))
        self.green_starting_tile_3.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                           "background-image: url(../graphics/counter-green.png);\n"
                                                           "background-repeat:no-repeat;"))
        self.green_starting_tile_3.setText(_fromUtf8(""))
        self.green_starting_tile_3.setObjectName(_fromUtf8("green_starting_tile_3"))
        self.red_starting_tile_0 = QtGui.QPushButton(Dialog)
        self.red_starting_tile_0.setGeometry(QtCore.QRect(673, 70, 43, 44))
        self.red_starting_tile_0.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                         "background-image: url(../graphics/counter-red.png);\n"
                                                         "background-repeat:no-repeat;"))
        self.red_starting_tile_0.setText(_fromUtf8(""))
        self.red_starting_tile_0.setObjectName(_fromUtf8("red_starting_tile_0"))
        self.red_starting_tile_1 = QtGui.QPushButton(Dialog)
        self.red_starting_tile_1.setGeometry(QtCore.QRect(723, 70, 43, 44))
        self.red_starting_tile_1.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                         "background-image: url(../graphics/counter-red.png);\n"
                                                         "background-repeat:no-repeat;"))
        self.red_starting_tile_1.setText(_fromUtf8(""))
        self.red_starting_tile_1.setObjectName(_fromUtf8("red_starting_tile_1"))
        self.red_starting_tile_2 = QtGui.QPushButton(Dialog)
        self.red_starting_tile_2.setGeometry(QtCore.QRect(673, 120, 43, 44))
        self.red_starting_tile_2.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                         "background-image: url(../graphics/counter-red.png);\n"
                                                         "background-repeat:no-repeat;"))
        self.red_starting_tile_2.setText(_fromUtf8(""))
        self.red_starting_tile_2.setObjectName(_fromUtf8("red_starting_tile_2"))
        self.red_starting_tile_3 = QtGui.QPushButton(Dialog)
        self.red_starting_tile_3.setGeometry(QtCore.QRect(723, 120, 43, 44))
        self.red_starting_tile_3.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                         "background-image: url(../graphics/counter-red.png);\n"
                                                         "background-repeat:no-repeat;"))
        self.red_starting_tile_3.setText(_fromUtf8(""))
        self.red_starting_tile_3.setObjectName(_fromUtf8("red_starting_tile_3"))
        self.tile_0 = QtGui.QPushButton(Dialog)
        self.tile_0.setGeometry(QtCore.QRect(172, 294, 43, 44))
        self.tile_0.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_0.setText(_fromUtf8(""))
        self.tile_0.setObjectName(_fromUtf8("tile_0"))
        self.tile_1 = QtGui.QPushButton(Dialog)
        self.tile_1.setGeometry(QtCore.QRect(227, 294, 43, 43))
        self.tile_1.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_1.setText(_fromUtf8(""))
        self.tile_1.setObjectName(_fromUtf8("tile_1"))
        self.tile_2 = QtGui.QPushButton(Dialog)
        self.tile_2.setGeometry(QtCore.QRect(281, 294, 43, 43))
        self.tile_2.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_2.setText(_fromUtf8(""))
        self.tile_2.setObjectName(_fromUtf8("tile_2"))
        self.tile_3 = QtGui.QPushButton(Dialog)
        self.tile_3.setGeometry(QtCore.QRect(336, 294, 43, 43))
        self.tile_3.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_3.setText(_fromUtf8(""))
        self.tile_3.setObjectName(_fromUtf8("tile_3"))
        self.tile_4 = QtGui.QPushButton(Dialog)
        self.tile_4.setGeometry(QtCore.QRect(394, 294, 43, 43))
        self.tile_4.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_4.setText(_fromUtf8(""))
        self.tile_4.setObjectName(_fromUtf8("tile_4"))
        self.tile_5 = QtGui.QPushButton(Dialog)
        self.tile_5.setGeometry(QtCore.QRect(394, 240, 43, 43))
        self.tile_5.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_5.setText(_fromUtf8(""))
        self.tile_5.setObjectName(_fromUtf8("tile_5"))
        self.tile_6 = QtGui.QPushButton(Dialog)
        self.tile_6.setGeometry(QtCore.QRect(394, 186, 43, 43))
        self.tile_6.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_6.setText(_fromUtf8(""))
        self.tile_6.setObjectName(_fromUtf8("tile_6"))
        self.tile_7 = QtGui.QPushButton(Dialog)
        self.tile_7.setGeometry(QtCore.QRect(394, 132, 43, 43))
        self.tile_7.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_7.setText(_fromUtf8(""))
        self.tile_7.setObjectName(_fromUtf8("tile_7"))
        self.tile_8 = QtGui.QPushButton(Dialog)
        self.tile_8.setGeometry(QtCore.QRect(394, 78, 43, 43))
        self.tile_8.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_8.setText(_fromUtf8(""))
        self.tile_8.setObjectName(_fromUtf8("tile_8"))
        self.tile_9 = QtGui.QPushButton(Dialog)
        self.tile_9.setGeometry(QtCore.QRect(452, 78, 43, 43))
        self.tile_9.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_9.setText(_fromUtf8(""))
        self.tile_9.setObjectName(_fromUtf8("tile_9"))
        self.tile_10 = QtGui.QPushButton(Dialog)
        self.tile_10.setGeometry(QtCore.QRect(510, 78, 43, 43))
        self.tile_10.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_10.setText(_fromUtf8(""))
        self.tile_10.setObjectName(_fromUtf8("tile_10"))
        self.tile_11 = QtGui.QPushButton(Dialog)
        self.tile_11.setGeometry(QtCore.QRect(510, 132, 43, 43))
        self.tile_11.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_11.setText(_fromUtf8(""))
        self.tile_11.setObjectName(_fromUtf8("tile_11"))
        self.tile_12 = QtGui.QPushButton(Dialog)
        self.tile_12.setGeometry(QtCore.QRect(510, 186, 43, 43))
        self.tile_12.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_12.setText(_fromUtf8(""))
        self.tile_12.setObjectName(_fromUtf8("tile_12"))
        self.tile_13 = QtGui.QPushButton(Dialog)
        self.tile_13.setGeometry(QtCore.QRect(510, 240, 43, 43))
        self.tile_13.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_13.setText(_fromUtf8(""))
        self.tile_13.setObjectName(_fromUtf8("tile_13"))
        self.tile_14 = QtGui.QPushButton(Dialog)
        self.tile_14.setGeometry(QtCore.QRect(510, 294, 43, 43))
        self.tile_14.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_14.setText(_fromUtf8(""))
        self.tile_14.setObjectName(_fromUtf8("tile_14"))
        self.tile_15 = QtGui.QPushButton(Dialog)
        self.tile_15.setGeometry(QtCore.QRect(568, 294, 43, 43))
        self.tile_15.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_15.setText(_fromUtf8(""))
        self.tile_15.setObjectName(_fromUtf8("tile_15"))
        self.tile_16 = QtGui.QPushButton(Dialog)
        self.tile_16.setGeometry(QtCore.QRect(626, 294, 43, 43))
        self.tile_16.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_16.setText(_fromUtf8(""))
        self.tile_16.setObjectName(_fromUtf8("tile_16"))
        self.tile_17 = QtGui.QPushButton(Dialog)
        self.tile_17.setGeometry(QtCore.QRect(684, 294, 43, 43))
        self.tile_17.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_17.setText(_fromUtf8(""))
        self.tile_17.setObjectName(_fromUtf8("tile_17"))
        self.tile_18 = QtGui.QPushButton(Dialog)
        self.tile_18.setGeometry(QtCore.QRect(742, 294, 43, 43))
        self.tile_18.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_18.setText(_fromUtf8(""))
        self.tile_18.setObjectName(_fromUtf8("tile_18"))
        self.tile_19 = QtGui.QPushButton(Dialog)
        self.tile_19.setGeometry(QtCore.QRect(742, 348, 43, 43))
        self.tile_19.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_19.setText(_fromUtf8(""))
        self.tile_19.setObjectName(_fromUtf8("tile_19"))
        self.tile_20 = QtGui.QPushButton(Dialog)
        self.tile_20.setGeometry(QtCore.QRect(742, 402, 43, 43))
        self.tile_20.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_20.setText(_fromUtf8(""))
        self.tile_20.setObjectName(_fromUtf8("tile_20"))
        self.tile_21 = QtGui.QPushButton(Dialog)
        self.tile_21.setGeometry(QtCore.QRect(684, 402, 43, 43))
        self.tile_21.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_21.setText(_fromUtf8(""))
        self.tile_21.setObjectName(_fromUtf8("tile_21"))
        self.tile_22 = QtGui.QPushButton(Dialog)
        self.tile_22.setGeometry(QtCore.QRect(626, 402, 43, 43))
        self.tile_22.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_22.setText(_fromUtf8(""))
        self.tile_22.setObjectName(_fromUtf8("tile_22"))
        self.tile_23 = QtGui.QPushButton(Dialog)
        self.tile_23.setGeometry(QtCore.QRect(568, 402, 43, 43))
        self.tile_23.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_23.setText(_fromUtf8(""))
        self.tile_23.setObjectName(_fromUtf8("tile_23"))
        self.tile_24 = QtGui.QPushButton(Dialog)
        self.tile_24.setGeometry(QtCore.QRect(510, 402, 43, 43))
        self.tile_24.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_24.setText(_fromUtf8(""))
        self.tile_24.setObjectName(_fromUtf8("tile_24"))
        self.tile_25 = QtGui.QPushButton(Dialog)
        self.tile_25.setGeometry(QtCore.QRect(510, 456, 43, 43))
        self.tile_25.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_25.setText(_fromUtf8(""))
        self.tile_25.setObjectName(_fromUtf8("tile_25"))
        self.tile_26 = QtGui.QPushButton(Dialog)
        self.tile_26.setGeometry(QtCore.QRect(510, 510, 43, 43))
        self.tile_26.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_26.setText(_fromUtf8(""))
        self.tile_26.setObjectName(_fromUtf8("tile_26"))
        self.tile_27 = QtGui.QPushButton(Dialog)
        self.tile_27.setGeometry(QtCore.QRect(510, 563, 43, 43))
        self.tile_27.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_27.setText(_fromUtf8(""))
        self.tile_27.setObjectName(_fromUtf8("tile_27"))
        self.tile_28 = QtGui.QPushButton(Dialog)
        self.tile_28.setGeometry(QtCore.QRect(510, 619, 43, 43))
        self.tile_28.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_28.setText(_fromUtf8(""))
        self.tile_28.setObjectName(_fromUtf8("tile_28"))
        self.tile_29 = QtGui.QPushButton(Dialog)
        self.tile_29.setGeometry(QtCore.QRect(452, 619, 43, 43))
        self.tile_29.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_29.setText(_fromUtf8(""))
        self.tile_29.setObjectName(_fromUtf8("tile_29"))
        self.tile_30 = QtGui.QPushButton(Dialog)
        self.tile_30.setGeometry(QtCore.QRect(394, 619, 43, 43))
        self.tile_30.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_30.setText(_fromUtf8(""))
        self.tile_30.setObjectName(_fromUtf8("tile_30"))
        self.tile_31 = QtGui.QPushButton(Dialog)
        self.tile_31.setGeometry(QtCore.QRect(394, 563, 43, 43))
        self.tile_31.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_31.setText(_fromUtf8(""))
        self.tile_31.setObjectName(_fromUtf8("tile_31"))
        self.tile_32 = QtGui.QPushButton(Dialog)
        self.tile_32.setGeometry(QtCore.QRect(394, 510, 43, 43))
        self.tile_32.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_32.setText(_fromUtf8(""))
        self.tile_32.setObjectName(_fromUtf8("tile_32"))
        self.tile_33 = QtGui.QPushButton(Dialog)
        self.tile_33.setGeometry(QtCore.QRect(394, 456, 43, 43))
        self.tile_33.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_33.setText(_fromUtf8(""))
        self.tile_33.setObjectName(_fromUtf8("tile_33"))
        self.tile_34 = QtGui.QPushButton(Dialog)
        self.tile_34.setGeometry(QtCore.QRect(394, 402, 43, 43))
        self.tile_34.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_34.setText(_fromUtf8(""))
        self.tile_34.setObjectName(_fromUtf8("tile_34"))
        self.tile_35 = QtGui.QPushButton(Dialog)
        self.tile_35.setGeometry(QtCore.QRect(336, 402, 43, 43))
        self.tile_35.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_35.setText(_fromUtf8(""))
        self.tile_35.setObjectName(_fromUtf8("tile_35"))
        self.tile_36 = QtGui.QPushButton(Dialog)
        self.tile_36.setGeometry(QtCore.QRect(281, 402, 43, 43))
        self.tile_36.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_36.setText(_fromUtf8(""))
        self.tile_36.setObjectName(_fromUtf8("tile_36"))
        self.tile_37 = QtGui.QPushButton(Dialog)
        self.tile_37.setGeometry(QtCore.QRect(227, 402, 43, 43))
        self.tile_37.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_37.setText(_fromUtf8(""))
        self.tile_37.setObjectName(_fromUtf8("tile_37"))
        self.tile_38 = QtGui.QPushButton(Dialog)
        self.tile_38.setGeometry(QtCore.QRect(172, 402, 43, 43))
        self.tile_38.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_38.setText(_fromUtf8(""))
        self.tile_38.setObjectName(_fromUtf8("tile_38"))
        self.tile_39 = QtGui.QPushButton(Dialog)
        self.tile_39.setGeometry(QtCore.QRect(172, 348, 43, 43))
        self.tile_39.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.tile_39.setText(_fromUtf8(""))
        self.tile_39.setObjectName(_fromUtf8("tile_39"))
        self.blue_home_tile_1 = QtGui.QPushButton(Dialog)
        self.blue_home_tile_1.setGeometry(QtCore.QRect(281, 348, 43, 43))
        self.blue_home_tile_1.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.blue_home_tile_1.setText(_fromUtf8(""))
        self.blue_home_tile_1.setObjectName(_fromUtf8("blue_home_tile_1"))
        self.blue_home_tile_2 = QtGui.QPushButton(Dialog)
        self.blue_home_tile_2.setGeometry(QtCore.QRect(336, 348, 43, 43))
        self.blue_home_tile_2.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.blue_home_tile_2.setText(_fromUtf8(""))
        self.blue_home_tile_2.setObjectName(_fromUtf8("blue_home_tile_2"))
        self.blue_home_tile_3 = QtGui.QPushButton(Dialog)
        self.blue_home_tile_3.setGeometry(QtCore.QRect(394, 348, 43, 43))
        self.blue_home_tile_3.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.blue_home_tile_3.setText(_fromUtf8(""))
        self.blue_home_tile_3.setObjectName(_fromUtf8("blue_home_tile_3"))
        self.red_home_tile_0 = QtGui.QPushButton(Dialog)
        self.red_home_tile_0.setGeometry(QtCore.QRect(452, 132, 43, 43))
        self.red_home_tile_0.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.red_home_tile_0.setText(_fromUtf8(""))
        self.red_home_tile_0.setObjectName(_fromUtf8("red_home_tile_0"))
        self.red_home_tile_1 = QtGui.QPushButton(Dialog)
        self.red_home_tile_1.setGeometry(QtCore.QRect(452, 186, 43, 43))
        self.red_home_tile_1.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.red_home_tile_1.setText(_fromUtf8(""))
        self.red_home_tile_1.setObjectName(_fromUtf8("red_home_tile_1"))
        self.red_home_tile_2 = QtGui.QPushButton(Dialog)
        self.red_home_tile_2.setGeometry(QtCore.QRect(452, 240, 43, 43))
        self.red_home_tile_2.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.red_home_tile_2.setText(_fromUtf8(""))
        self.red_home_tile_2.setObjectName(_fromUtf8("red_home_tile_2"))
        self.red_home_tile_3 = QtGui.QPushButton(Dialog)
        self.red_home_tile_3.setGeometry(QtCore.QRect(452, 294, 43, 43))
        self.red_home_tile_3.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.red_home_tile_3.setText(_fromUtf8(""))
        self.red_home_tile_3.setObjectName(_fromUtf8("red_home_tile_3"))
        self.green_home_tile_0 = QtGui.QPushButton(Dialog)
        self.green_home_tile_0.setGeometry(QtCore.QRect(684, 348, 43, 43))
        self.green_home_tile_0.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.green_home_tile_0.setText(_fromUtf8(""))
        self.green_home_tile_0.setObjectName(_fromUtf8("green_home_tile_0"))
        self.green_home_tile_1 = QtGui.QPushButton(Dialog)
        self.green_home_tile_1.setGeometry(QtCore.QRect(626, 348, 43, 43))
        self.green_home_tile_1.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.green_home_tile_1.setText(_fromUtf8(""))
        self.green_home_tile_1.setObjectName(_fromUtf8("green_home_tile_1"))
        self.green_home_tile_2 = QtGui.QPushButton(Dialog)
        self.green_home_tile_2.setGeometry(QtCore.QRect(568, 348, 43, 43))
        self.green_home_tile_2.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.green_home_tile_2.setText(_fromUtf8(""))
        self.green_home_tile_2.setObjectName(_fromUtf8("green_home_tile_2"))
        self.green_home_tile_3 = QtGui.QPushButton(Dialog)
        self.green_home_tile_3.setGeometry(QtCore.QRect(510, 348, 43, 43))
        self.green_home_tile_3.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.green_home_tile_3.setText(_fromUtf8(""))
        self.green_home_tile_3.setObjectName(_fromUtf8("green_home_tile_3"))
        self.yellow_home_tile_3 = QtGui.QPushButton(Dialog)
        self.yellow_home_tile_3.setGeometry(QtCore.QRect(452, 402, 43, 43))
        self.yellow_home_tile_3.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.yellow_home_tile_3.setText(_fromUtf8(""))
        self.yellow_home_tile_3.setObjectName(_fromUtf8("yellow_home_tile_3"))
        self.yellow_home_tile_2 = QtGui.QPushButton(Dialog)
        self.yellow_home_tile_2.setGeometry(QtCore.QRect(452, 456, 43, 43))
        self.yellow_home_tile_2.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.yellow_home_tile_2.setText(_fromUtf8(""))
        self.yellow_home_tile_2.setObjectName(_fromUtf8("yellow_home_tile_2"))
        self.yellow_home_tile_1 = QtGui.QPushButton(Dialog)
        self.yellow_home_tile_1.setGeometry(QtCore.QRect(452, 510, 43, 43))
        self.yellow_home_tile_1.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.yellow_home_tile_1.setText(_fromUtf8(""))
        self.yellow_home_tile_1.setObjectName(_fromUtf8("yellow_home_tile_1"))
        self.yellow_home_tile_0 = QtGui.QPushButton(Dialog)
        self.yellow_home_tile_0.setGeometry(QtCore.QRect(452, 563, 43, 43))
        self.yellow_home_tile_0.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.yellow_home_tile_0.setText(_fromUtf8(""))
        self.yellow_home_tile_0.setObjectName(_fromUtf8("yellow_home_tile_0"))
        self.blue_home_tile_0 = QtGui.QPushButton(Dialog)
        self.blue_home_tile_0.setGeometry(QtCore.QRect(227, 348, 43, 43))
        self.blue_home_tile_0.setStyleSheet(_fromUtf8("background-color:TRANSPARENT;border:0;"))
        self.blue_home_tile_0.setText(_fromUtf8(""))
        self.blue_home_tile_0.setObjectName(_fromUtf8("blue_home_tile_0"))

        self.title = QtGui.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(840, 50, 381, 51))
        self.title.setStyleSheet(
            _fromUtf8("background-image:url(../graphics/title.png); background-repeat:no-repeat;"))
        self.title.setText(_fromUtf8(""))
        self.title.setObjectName(_fromUtf8("title"))
        self.startbutton = QtGui.QPushButton(Dialog)
        self.startbutton.setGeometry(QtCore.QRect(900, 140, 248, 73))
        self.startbutton.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                                 "background-image: url(../graphics/start.png);\n"
                                                 "background-repeat:no-repeat;"))
        self.startbutton.setText(_fromUtf8(""))
        self.startbutton.setObjectName(_fromUtf8("startbutton"))
        self.dice = QtGui.QPushButton(Dialog)
        self.dice.setGeometry(QtCore.QRect(939, 430, 171, 171))
        self.dice.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                          "background-image: url(../graphics/dice1.png);\n"
                                          "background-repeat:no-repeat;"))
        self.dice.setText(_fromUtf8(""))
        self.dice.setObjectName(_fromUtf8("dice"))
        self.turn_alert_label = QtGui.QLabel(Dialog)
        self.turn_alert_label.setGeometry(QtCore.QRect(920, 390, 221, 31))
        self.turn_alert_label.setStyleSheet(_fromUtf8("font-size:19px"))
        self.turn_alert_label.setObjectName(_fromUtf8("label_2"))
        self.player_color_label = QtGui.QLabel(Dialog)
        self.player_color_label.setGeometry(QtCore.QRect(950, 240, 111, 41))
        self.player_color_label.setStyleSheet(_fromUtf8("font-size:20px"))
        self.player_color_label.setObjectName(_fromUtf8("label_4"))
        self.player_color_placeholder = QtGui.QLabel(Dialog)
        self.player_color_placeholder.setGeometry(QtCore.QRect(1060, 240, 43, 44))
        self.player_color_placeholder.setStyleSheet(_fromUtf8("background-color:transparent;border:0;\n"
                                             "background-image: url(../graphics/counter-red.png);\n"
                                             "background-repeat:no-repeat;"))
        self.player_color_placeholder.setText(_fromUtf8(""))
        self.player_color_placeholder.setObjectName(_fromUtf8("label_5"))
        self.player_color_label.setText(_translate("Dialog", "Twój kolor:", None))
        self.turn_alert_label.setText(_translate("Dialog", "Twoja kolej. Rzuć kostką!", None))

        LayoutMethodsInserter.insert_methods(self)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Do Not Get Angry", None))


if __name__ == "__main__":
    import sys

    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
